In [1]:
from sklearn.datasets import load_iris

In [8]:
iris=load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [19]:
#feature data X metric that is why upper case
X=iris.data
##Target data y vector only so lower case
y=iris.target

In [12]:
print("data of iris ", type(x))
print("data of iris ", type(y))
#print(x)
print(y)

data of iris  <class 'numpy.ndarray'>
data of iris  <class 'numpy.ndarray'>
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [15]:
print(iris.data.shape)
print(iris.target.shape)

(150, 4)
(150,)


In [10]:
feature_name = iris.feature_names
target_name = iris.target_names
print("feature_name of iris ", feature_name)
print("target_name of iris ", target_name)

feature_name of iris  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
target_name of iris  ['setosa' 'versicolor' 'virginica']


#1 feature and response to be passed intot the machine learning model seperately 
#2 only numbers can be expected not the characters and strings 
#3 response about always be numerics 
#4 Everything should be in numpy array ndarray 
#5 feature adn response about - feature has to has two demensions - row *colums 
and target should be in one dimensions

#KNN Algorithm

1.Import the class that you want to use for the modeling the data 

In [21]:
from sklearn.neighbors import KNeighborsClassifier

2."Instantiate the "estimators
Estimators is model in scikit learn terms 
Instantiate mean make the instance

In [22]:
knn=KNeighborsClassifier(n_neighbors=1)

In [23]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')


Fit the model with the Data

In [26]:
knn.fit(X,y)

#pass the feature metrics and response variable to the fit method in the Knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=1, p=2,
           weights='uniform')

Make Predictions for the new and out of sample observations

In [29]:
X_new=[[1,2,3,4],[1,3,5,7]]

In [30]:
knn.predict(X_new)

array([2, 2])

#Using the Different Value of K


In [31]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)
knn.predict(X_new)

array([1, 2])

#Using the Logistic Regression Model in SKlearn

In [33]:
from sklearn.linear_model import LogisticRegression

In [34]:
logreg= LogisticRegression()

In [35]:
logreg.fit(X,y)

/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [36]:
logreg.predict(X_new)

array([2, 2])

Model evaluation procedures
Train and Test 

In [37]:
y_Pred=logreg.predict(X)

In [38]:
len(y_Pred)

150

#Classification Accuracy Logistic Regression 


In [42]:
from sklearn import metrics
print(metrics.accuracy_score(y,y_Pred))

0.96


#Classification Accuracy KNN 


In [43]:
y_pred=knn.predict(X)

In [44]:
print(metrics.accuracy_score(y,y_pred))

0.9666666666666667
